config/routes.rb
Rails.application.routes.draw do
  resources :eventos
  root 'pages#home', as: 'home'
  get 'pages/home'
  resources :jogos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :jogo
end

app/models/jogo.rb
class Jogo < ApplicationRecord
	has_many :jogos_plataformas, dependent: :destroy
	has_many :plataformas, through: :jogos_plataformas
	#has_and_belongs_to_many :plataformas
end

app/models/jogos_plataforma.rb
class JogosPlataforma < ApplicationRecord
  belongs_to :jogo
  belongs_to :plataforma
end

app/models/plataforma.rb
class Plataforma < ApplicationRecord
	has_many :jogos_plataformas, dependent: :destroy
	has_many :jogos, through: :jogos_plataformas
	#has_and_belongs_to_many :jogos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:nome, :dataInicio, :dataFim, :jogo_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def sign_up
    @user = User.new
  end
end

app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  before_action :set_jogo, only: [:show, :edit, :update, :destroy]

  # GET /jogos
  # GET /jogos.json
  def index
    @jogos = Jogo.all
  end

  # GET /jogos/1
  # GET /jogos/1.json
  def show
  end

  # GET /jogos/new
  def new
    @jogo = Jogo.new
  end

  # GET /jogos/1/edit
  def edit
  end

  # POST /jogos
  # POST /jogos.json
  def create
    @jogo = Jogo.new(jogo_params)

    respond_to do |format|
      if @jogo.save
        format.html { redirect_to @jogo, notice: 'Jogo was successfully created.' }
        format.json { render :show, status: :created, location: @jogo }
      else
        format.html { render :new }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jogos/1
  # PATCH/PUT /jogos/1.json
  def update
    respond_to do |format|
      if @jogo.update(jogo_params)
        format.html { redirect_to @jogo, notice: 'Jogo was successfully updated.' }
        format.json { render :show, status: :ok, location: @jogo }
      else
        format.html { render :edit }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jogos/1
  # DELETE /jogos/1.json
  def destroy
    @jogo.destroy
    respond_to do |format|
      format.html { redirect_to jogos_url, notice: 'Jogo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jogo
      @jogo = Jogo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jogo_params
      params.require(:jogo).permit(:nome, :plataforma_ids)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @jogos = Jogo.last(5).reverse
    @eventos = Evento.last(5).reverse
  end
end

app/controllers/users_controller.rb
# Never trust parameters from the scary internet, only allow the white list through.
def user_params
  params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/jogos_helper.rb
module JogosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/eventos/_form.html.erb
<%= form_with(model: evento, local: true) do |form| %>
  <% if evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :dataInicio %>
    <%= form.datetime_select :dataInicio %>
  </div>

  <div class="field">
    <%= form.label :dataFim %>
    <%= form.datetime_select :dataFim %>
  </div>

  <div class="field">
    <%= form.label :jogo_id %>
    <%= form.text_field :jogo_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventos</h1>

<table class="table table-hover table-nonfluid">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data de Início</th>
      <th>Data de Fim</th>
      <th>Jogo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.nome %></td>
        <td><%= evento.dataInicio %></td>
        <td><%= evento.dataFim %></td>
        <td><%= evento.jogo.nome %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @evento.nome %>
</p>

<p>
  <strong>Datainicio:</strong>
  <%= @evento.dataInicio %>
</p>

<p>
  <strong>Datafim:</strong>
  <%= @evento.dataFim %>
</p>

<p>
  <strong>Jogo:</strong>
  <%= @evento.jogo %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>

app/views/home/_footer.html.erb
<div class="footer">

 <div class="footer_content">
   <p>footer information will go here</p>

  </div>
    
</div>

app/views/home/index.html.erb
  <div class="mainContent">
    
    <div class="heroBanner col_4">
            
      <div class="callToAction heroBanner_col_2_reverse">
        <h2 class="heroTitle">Call to Action</h2>
        <p class="heroDescription">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam nihil tenetur doloremque porro libero molestiae recusandae ab unde corporis.</p>
        
        <form class="heroForm">
        <label for="email">Enter your email to get started</label>
        <br>
        <input id="email" type="email" />
        <input class="submitEmail" type="submit" value="Submit" />
        </form>
        
      </div><!-- end call to action -->
      
      <div class="heroBanner_col_2">
        <img src="<%= asset_path "laptop_screenshot.png" %>" class="laptopIllustration" alt="laptop"/>
      </div><!-- end laptop illustration -->

    </div><!-- end hero banner -->
    
    <div class="grid">
    
      <h1 class="largeHeader">OurAgendaApp</h1>
      <p class="appDescription col_4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam nihil tenetur doloremque porro libero molestiae recusandae ab unde corporis nesciunt at odit nemo temporibus numquam delectus. Voluptatum autem beatae ex.</p>
      
      <div class="appFeature col_2">
      <h3 class="appFeature_header">Users</h2>
      <p class="appFeature_description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam nihil tenetur doloremque porro libero molestiae recusandae ab unde corporis.</p>
      </div><!-- end appFeature_users -->
      
      
      <div class="appFeature col_2">
      <h3 class="appFeature_header">Agenda Items</h2>
      <p class="appFeature_description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam nihil tenetur doloremque porro libero molestiae recusandae ab unde corporis.</p>
      </div><!-- end appFeatures_agendaItems -->
            
      <div class="appFeature col_2">
      <h3 class="appFeature_header">Action Items</h2>
      <p class="appFeature_description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam nihil tenetur doloremque porro libero molestiae recusandae ab unde corporis.</p>
      </div><!-- end appFeatures_actionItems -->
    
      <div class="appFeature col_2">
      <h3 class="appFeature_header">Meetings</h2>
      <p class="appFeature_description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam nihil tenetur doloremque porro libero molestiae recusandae ab unde corporis.</p>
      </div><!-- end appFeatures_meetings -->
            
      <div class="facebook_facepile">
      </div><!-- end facebook_facepile -->
            
      <div class="twitter_tweets">
      </div><!-- end twitter_tweets -->
      
    </div><!-- end grid -->
  </div><!-- end mainContent -->

app/views/home/sign_up.html.erb
<!-- app/views/home/sign_up.html.erb -->
<div class="mainContent">
  <div class="grid">
    <h1 class="largeHeader">Sign up</h1>
    <p class="centeredDescription col_4">Already signed up? You can <a href="">log in here.</a></p>
    <div class="col_1">
      <%= form_for :user, class: "signupForm" do |f| %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "shortInput" %> <br />

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "shortInput" %> <br />

      <%= f.label :email, "Email Address" %>
      <%= f.text_field :email, class: "shortInput" %> <br />

      <%= f.label :password %>
      <%= f.password_field :password, class: "shortInput" %> <br />

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: "shortInput" %> <br />

      <%= f.submit "Create account", class: "button createAccount" %>

    <% end %>

    </div><!-- end centered_col contact form -->

    <div class="centered_col">
    </div>

  </div><!-- end grid -->
</div><!-- end mainContent -->

app/views/jogos/_form.html.erb
<%= form_with(model: jogo, local: true) do |form| %>
  <% if jogo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jogo.errors.count, "error") %> prohibited this jogo from being saved:</h2>

      <ul>
      <% jogo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

<% for plataforma in Plataforma.all %>
<div>
  <%= check_box_tag "product[plataforma_ids][]", plataforma.id, @jogo.plataformas.include?(plataforma) %>
  <%= plataforma.nome %>
</div>
<% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jogos/edit.html.erb
<h1>Editing Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Show', @jogo %> |
<%= link_to 'Back', jogos_path %>

app/views/jogos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jogos</h1>

<table class="table table-hover table-nonfluid">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jogos.each do |jogo| %>
      <tr>
        <td><%= jogo.nome %></td>
        <td class="text-center"><%= link_to '<span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>'.html_safe, jogo %></td>
        <td class="text-center"><%= link_to '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>'.html_safe, edit_jogo_path(jogo) %></td>
        <td class="text-center"><%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>'.html_safe, jogo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="tab">
<%= link_to '<span class="glyphicon glyphicon-home" aria-hidden="true"></span>'.html_safe, pages_home_path %>
  <span class="glyphicon glyphicon-option-vertical" aria-hidden="true"></span>
<%= link_to '<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>'.html_safe, new_jogo_path %>
</div>

app/views/jogos/new.html.erb
<h1>New Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Back', jogos_path %>

app/views/jogos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @jogo.nome %>
</p>

<p>
    Plataformas: <%= @jogo.plataformas.map(&:nome).join(',') %>
</p>

<%= link_to 'Edit', edit_jogo_path(@jogo) %> |
<%= link_to 'Back', jogos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solucoes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Bem-vindo(a)!</h1>
<h2>Últimos jogos adicionados:</h2>

<table class="table table-hover table-nonfluid">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jogos.each do |jogo| %>
      <tr>
        <td><%= jogo.nome %></td>
        <td class="text-center"><%= link_to '<span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>'.html_safe, jogo %></td>
        <td><%= link_to 'Add', jogo, method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="tab">
<%= link_to 'Ver todos os jogos'.html_safe, jogos_path %>
</div>

<h2>Últimos eventos adicionados:</h2>

<table class="table table-hover table-nonfluid">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data de Início</th>
      <th>Data de Fim</th>
      <th>Jogo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.nome %></td>
        <td><%= evento.dataInicio %></td>
        <td><%= evento.dataFim %></td>
        <td><%= evento.jogo.nome %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="tab">
<%= link_to 'Ver todos os eventos'.html_safe, eventos_path %>
</div>